version: '3'
services:

  db:
    image: postgres:db
    build:
      context: .
      dockerfile: postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - .database:/var/lib/postgresql/data

  # backend:
  #   image: backend:latest
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - backend/.env

  # web:
  #   image: web:latest
  #   build:
  #     context: .
  #     dockerfile: web/Dockerfile
  #   ports:
  #     - "8888:80"
